"""empty message

Revision ID: 1b8cb1f182a1
Revises: c1d09b00f711
Create Date: 2017-05-31 18:31:13.438674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8cb1f182a1'
down_revision = 'c1d09b00f711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'employee_manager_fkey', 'employee', type_='foreignkey')
    op.drop_column('employee', 'manager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('manager', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'employee_manager_fkey', 'employee', 'employee', ['manager'], ['id'])
    # ### end Alembic commands ###
