"""empty message

Revision ID: 63bc504eaf2b
Revises: d2d78e5821c1
Create Date: 2017-06-07 10:39:44.262012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bc504eaf2b'
down_revision = 'd2d78e5821c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('startdate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'startdate')
    # ### end Alembic commands ###
