"""empty message

Revision ID: 9d0cd8cfec8d
Revises: 5fd3697a615b
Create Date: 2017-05-31 16:25:49.905058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0cd8cfec8d'
down_revision = '5fd3697a615b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('leave', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave', 'status')
    op.drop_column('leave', 'address')
    # ### end Alembic commands ###
