"""empty message

Revision ID: d2d78e5821c1
Revises: 0c92239737b7
Create Date: 2017-06-05 19:39:49.808775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d78e5821c1'
down_revision = '0c92239737b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('picture', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'picture')
    # ### end Alembic commands ###
